-- Disable Row Level Security for all tables
-- Run this in Supabase SQL Editor if you're getting permission errors

ALTER TABLE "User" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Exercise" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Program" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Day" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "DayExercise" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Workout" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Set" DISABLE ROW LEVEL SECURITY;


